import type { Metadata } from "next";
import "@/app/globals.css";
import NavigationDock from "@/components/non-admin-components/NavigationDock";
import ParticlesBackground from "@/components/non-admin-components/ParticlesBackground";

export const metadata: Metadata = {
	title: "Blog",
	description: "Generated by Me",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ParticlesBackground>
					<NavigationDock />
					{children}
				</ParticlesBackground>
			</body>
		</html>
	);
}
